#配置文件
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  #mvc:
    #throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    username: root
    password: waws19920810!
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.12.197.172:3306/programedge?characterEncoding=UTF-8&useUnicode=true&useSSL=false

mybatis:
  type-aliases-package: pw.androidthanatos.blog.entity