#配置文件
server:
  #port: 8080
  port: 80
  tomcat:
    uri-encoding: UTF-8

spring:
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    throw-exception-if-no-handler-found: true
  #启用静态资源html
  resources:
    add-mappings: true
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: waws19920810!
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.12.197.172:3306/programedge?characterEncoding=UTF-8&useUnicode=true&useSSL=false
  mail:
    host: smtp.qq.com
    username: 523928638@qq.com
    password: mocgsfjqomivcbdg
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1GB
mybatis:
  type-aliases-package: pw.androidthanatos.blog.entity

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql